# Generated by Django 2.2.13 on 2021-04-07 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qol', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shops', to='webapp.Order', verbose_name='Заказ')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='webapp.Shop', verbose_name='Продукт')),
            ],
        ),
    ]
